import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <nav
        style={{
          width: "100%",
          background: "teal",
          fontSize: "30px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Link href="/">
          <button type="button" style={{ padding: "10px", margin: "10px" }}>
            home
          </button>
        </Link>
        <Link href="/posts" >
          <button type="button" style={{ padding: "10px", margin: "10px" }}>Posts</button>
        </Link>
        <Link href="/articls" >
          <button type="button" style={{ padding: "10px", margin: "10px" }}>Articls</button>
        </Link>
      </nav>
      
      {children}</body>
    </html>
  );
}
